spring:
  activemq:
    broker-url: tcp://localhost:61616

queue:
  gateway: gateway.q
  gateway-reply: gateway.reply.q
  adapter: adapter.q

channel:
  request:
    start: request.ch
    first: request.ch.1
    second: request.ch.2
  reply: reply.ch
  subscriber:
    result_1: subscriber.result.1
    result_2: subscriber.result.2
