spring:
  activemq:
    broker-url: tcp://localhost:61616

queue:
  boot: boot.q
  boot-reply: boot.reply.q

channel:
  request:
    start: request.ch
    first: request.ch.1
    second: request.ch.2
  reply: reply.ch
  subscriber:
    result_1: subscriber.result.1
    result_2: subscriber.result.2
